### ISSUE TITLE
User portfolio website link not working

### ISSUE THREAD

**Issue by mxdvf** [aritrasen12345/github-user-analytics#1]
In the project, portfolio links with the protocol https:// are not working since the output comes out to be `https://https//[thewebsitelink.com]`. This is because of the extra https protocol used in [line36](https://github.com/aritrasen12345/github-user-analytics/blob/main/src/components/Card.js#L36) of `src/components/Card.js`

**Comment by aritrasen12345** [comment]
Thanks a lot, @mehul-srivastava for pointing it out.
